### ISSUE TITLE
About MPCFullState msg 

### ISSUE THREAD

**Issue by YouthKim** [wuwushrek/sde4mbrl_px4#1]
You've done a fantastic job and I'm currently studying your code. But I have a problem, I didn't find any documentation about the specifics of the MPCFullState message, can you provide that part?

**Comment by wuwushrek** [comment]
Hi there, I just changed the README.md to point to the right branch where MPCFUllState is described: https://github.com/wuwushrek/mavros/tree/mpc_franck
